/*---------------------------------------------------------------------------------------
 * Filename       : mb_preset_tb.sv
 *
 * Purpose        : This is a verilog testbench source generated by create_testbench Tcl
 *                  command for the selected instance scope. The testbench includes a
 *                  verilog stimulus source file that will provide the input waveform for
 *                  the instantiated DUT (Design Under Test).
 *
 * Instance Name  : mb_preset
 * Selected Scope : /mb_preset_wrapper/mb_preset_i
 * Stimulus File  : mb_preset.xil_tb_vectors.sv
 *
 * IMPORTANT      : In case you delete this testbench source from the project, then the
 *                  stimulus file becomes obsolete and must be deleted manually from the
 *                  simulation fileset.
 *
 * Date created   : 09/20/2022 (15:29:00)
 *---------------------------------------------------------------------------------------*/
`timescale 1ps/1ps

module tb ();

reg default_sysclk1_300_clk_n;
reg default_sysclk1_300_clk_p;
reg [3:0] dip_switches_4bits_tri_i;
reg iic_main_scl_i;
reg iic_main_sda_i;
reg [4:0] push_buttons_5bits_tri_i;
reg reset;
reg rs232_uart_rxd;
wire iic_main_scl_o;
wire iic_main_scl_t;
wire iic_main_sda_o;
wire iic_main_sda_t;
wire [7:0] led_8bits_tri_o;
wire rs232_uart_txd;

//`include "mb_preset.xil_tb_vectors.sv"

initial begin
  $timeformat(-3,0,"ms",10);
  `ifdef VCS
    $dumpfile("comp_mb_preset.vcd");
    $dumpvars(1, demo_tb.DUT);
  //$dumpports(demo_tb.DUT, "comp_mb_preset.vcd");
  //$dumpfile("full_comp_mb_preset.vcd");
  //$dumpvars(0, demo_tb.DUT);
  `else
  `ifdef INCA
    $dumpports(demo_tb.DUT, "comp_mb_preset.vcd");
  //$dumpfile("full_comp_mb_preset.vcd");
  //$dumpvars(0, demo_tb.DUT);
  `else
  `ifdef MODEL_TECH
    $dumpports(demo_tb.DUT, "comp_mb_preset.vcd");
  //$dumpfile("full_comp_mb_preset.vcd");
  //$dumpvars(0, demo_tb.DUT);
  `else
    $dumpfile("comp_mb_preset.vcd");
    $dumpvars(1, demo_tb.DUT);
  //$dumpfile("full_comp_mb_preset.vcd");
  //$dumpvars(0, demo_tb.DUT);
  `endif
  `endif
  `endif
end

wire reset_p;
wire reset_n;
clkgen clkgen (
    .clk_n (default_sysclk1_300_clk_n),
    .clk_p (default_sysclk1_300_clk_p),
    .reset_p (reset),
    .reset_n (reset_n)
);

mb_preset DUT (
  .default_sysclk1_300_clk_n (default_sysclk1_300_clk_n),
  .default_sysclk1_300_clk_p (default_sysclk1_300_clk_p),
  .dip_switches_4bits_tri_i (dip_switches_4bits_tri_i),
  .iic_main_scl_i (iic_main_scl_i),
  .iic_main_sda_i (iic_main_sda_i),
  .push_buttons_5bits_tri_i (push_buttons_5bits_tri_i),
  .reset (reset),
  .rs232_uart_rxd (rs232_uart_rxd),
  .iic_main_scl_o (iic_main_scl_o),
  .iic_main_scl_t (iic_main_scl_t),
  .iic_main_sda_o (iic_main_sda_o),
  .iic_main_sda_t (iic_main_sda_t),
  .led_8bits_tri_o (led_8bits_tri_o),
  .rs232_uart_txd (rs232_uart_txd)
);

endmodule
