# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_dlmb_v10_0/top_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dlmb_v10_0 || ORIG_REF_NAME==top_dlmb_v10_0} -quiet] -quiet

# IP: bd/top/ip/top_ilmb_v10_0/top_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ilmb_v10_0 || ORIG_REF_NAME==top_ilmb_v10_0} -quiet] -quiet

# IP: bd/top/ip/top_dlmb_bram_if_cntlr_0/top_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==top_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/top/ip/top_ilmb_bram_if_cntlr_0/top_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==top_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/top/ip/top_lmb_bram_0/top_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_lmb_bram_0 || ORIG_REF_NAME==top_lmb_bram_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_clk_wiz_1_100M_0/top_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==top_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/top/ip/top_clk_wiz_1_0/top_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_clk_wiz_1_0 || ORIG_REF_NAME==top_clk_wiz_1_0} -quiet] -quiet

# IP: bd/top/ip/top_mdm_1_0/top_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_mdm_1_0 || ORIG_REF_NAME==top_mdm_1_0} -quiet] -quiet

# IP: bd/top/ip/top_microblaze_0_0/top_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_microblaze_0_0 || ORIG_REF_NAME==top_microblaze_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xbar_0/top_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xbar_0 || ORIG_REF_NAME==top_xbar_0} -quiet] -quiet

# IP: bd/top/ip/top_microblaze_0_axi_periph_0/top_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_microblaze_0_axi_periph_0 || ORIG_REF_NAME==top_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_uartlite_0_0/top_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_uartlite_0_0 || ORIG_REF_NAME==top_axi_uartlite_0_0} -quiet] -quiet

# XDC: /home/fae/mbzuart_v21p2/vivado/hw/hw.gen/sources_1/bd/top/top_ooc.xdc
