set_property SRC_FILE_INFO {cfile:/home/fae/mbzuart_v21p2/vivado/hw/hw.srcs/constrs_1/new/constraints.xdc rfile:../../../hw.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BN53 [get_ports CLK_clk_p]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BK44 [get_ports RST]
