/*---------------------------------------------------------------------------------------
 * Filename       : top_wrapper_tb.sv
 *
 * Purpose        : This is a verilog testbench source generated by create_testbench Tcl
 *                  command for the selected instance scope. The testbench includes a
 *                  verilog stimulus source file that will provide the input waveform for
 *                  the instantiated DUT (Design Under Test).
 *
 * Instance Name  : top_wrapper
 * Selected Scope : /top_wrapper
 * Stimulus File  : top_wrapper.xil_tb_vectors.sv
 *
 * IMPORTANT      : In case you delete this testbench source from the project, then the
 *                  stimulus file becomes obsolete and must be deleted manually from the
 *                  simulation fileset.
 *
 * Date created   : 03/15/2023 (13:23:54)
 *---------------------------------------------------------------------------------------*/
`timescale 1ps/1ps

module tb ();

reg CLK_clk_n;
reg CLK_clk_p;
reg RST;

`include "top_wrapper.xil_tb_vectors.sv"

initial begin
  $timeformat(-3,0,"ms",10);
  `ifdef VCS
    $dumpfile("comp_top_wrapper.vcd");
    $dumpvars(1, tb.DUT);
  //$dumpports(tb.DUT, "comp_top_wrapper.vcd");
  //$dumpfile("full_comp_top_wrapper.vcd");
  //$dumpvars(0, tb.DUT);
  `else
  `ifdef INCA
    $dumpports(tb.DUT, "comp_top_wrapper.vcd");
  //$dumpfile("full_comp_top_wrapper.vcd");
  //$dumpvars(0, tb.DUT);
  `else
  `ifdef MODEL_TECH
    $dumpports(tb.DUT, "comp_top_wrapper.vcd");
  //$dumpfile("full_comp_top_wrapper.vcd");
  //$dumpvars(0, tb.DUT);
  `else
    $dumpfile("comp_top_wrapper.vcd");
    $dumpvars(1, tb.DUT);
  //$dumpfile("full_comp_top_wrapper.vcd");
  //$dumpvars(0, tb.DUT);
  `endif
  `endif
  `endif
end

top_wrapper DUT (
  .CLK_clk_n (CLK_clk_n),
  .CLK_clk_p (CLK_clk_p),
  .RST (RST)
);

endmodule
